import type { Activity, Member, Project, Task, TeamKey } from "./types";

export const CURRENT_USER: Member = {
  id: "u-dexter",
  name: "Dexter",
  initials: "DX",
  color: "linear-gradient(135deg,#8b5cf6,#ec4899)",
};

export const MEMBERS: Member[] = [
  CURRENT_USER,
  { id: "u-admin", name: "Admin", initials: "AD", color: "linear-gradient(135deg,#3b82f6,#22d3ee)" },
  { id: "u-cn", name: "Charles N.", initials: "CN", color: "linear-gradient(135deg,#64748b,#94a3b8)" },
  { id: "u-ankit", name: "Ankit Dutta", initials: "AN", color: "linear-gradient(135deg,#f59e0b,#ef4444)" },
  { id: "u-maya", name: "Maya R.", initials: "MR", color: "linear-gradient(135deg,#10b981,#34d399)" },
  { id: "u-nils", name: "Nils B.", initials: "NB", color: "linear-gradient(135deg,#6366f1,#8b5cf6)" },
  { id: "u-sara", name: "Sara K.", initials: "SK", color: "linear-gradient(135deg,#ec4899,#f43f5e)" },
];

const iso = (d: string) => new Date(d).toISOString();

let seq = 0;
const next = () => seq++;

const RAW_TASKS: Omit<Task, "teams" | "activity">[] = [
  {
    id: "t-api-docs",
    title: "Write API Documentation",
    description:
      "Create clear and detailed API documentation to guide developers in using the inventory and sales metrics features effectively.",
    group: "todo",
    status: "backlog",
    priority: "high",
    labels: ["research", "design", "development", "testing", "deployment"],
    memberIds: ["u-admin", "u-nils"],
    reporterId: "u-dexter",
    dueDate: iso("2026-07-31"),
    startDate: iso("2026-01-10"),
    projectId: "p-login",
    order: next(),
    createdAt: iso("2026-06-01"),
    subtasks: [
      { id: "st-1", title: "Subtask 1", priority: "high", memberIds: ["u-dexter"], dueDate: iso("2026-09-12"), done: false },
      { id: "st-2", title: "Subtask 2", priority: "low", memberIds: ["u-cn"], dueDate: iso("2026-09-15"), done: false },
      { id: "st-3", title: "Subtask 3", priority: "medium", memberIds: [], dueDate: iso("2026-09-18"), done: false },
    ],
    comments: [
      { id: "c-1", authorId: "u-ankit", body: "Draft is ready for review.", createdAt: iso("2026-08-01") },
    ],
  },
  {
    id: "t-search",
    title: "Implement Search Function",
    description: "Add fuzzy search across tasks, members and labels.",
    group: "todo",
    status: "todo",
    priority: "medium",
    labels: ["development"],
    memberIds: ["u-admin"],
    reporterId: "u-dexter",
    dueDate: iso("2026-07-29"),
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-02"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-deploy",
    title: "Deploy to Production",
    description: "Ship the release candidate to production infrastructure.",
    group: "todo",
    status: "todo",
    priority: "urgent",
    labels: ["deployment"],
    memberIds: ["u-admin"],
    reporterId: "u-dexter",
    dueDate: iso("2026-07-29"),
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-03"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-review",
    title: "Code Review Completed",
    description: "Peer review of the checkout module.",
    group: "doing",
    status: "in_progress",
    priority: "high",
    labels: ["development"],
    memberIds: ["u-admin", "u-sara"],
    reporterId: "u-dexter",
    dueDate: iso("2026-07-29"),
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-04"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-mockups",
    title: "Design Mockups Finalized",
    description: "High-fidelity mockups for the dashboard revamp.",
    group: "doing",
    status: "in_progress",
    priority: "medium",
    labels: ["design", "deployment"],
    memberIds: ["u-admin"],
    reporterId: "u-dexter",
    dueDate: iso("2026-07-29"),
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-05"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-testing",
    title: "Feature Testing Passed",
    description: "Regression suite green for the billing feature.",
    group: "completed",
    status: "done",
    priority: "low",
    labels: ["testing"],
    memberIds: ["u-maya"],
    reporterId: "u-dexter",
    dueDate: iso("2026-07-30"),
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-06"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-ui-updated",
    title: "UI Design Updated",
    description: "Refined spacing and typography across the app.",
    group: "completed",
    status: "done",
    priority: "medium",
    labels: ["design"],
    memberIds: ["u-nils"],
    reporterId: "u-dexter",
    dueDate: iso("2026-07-31"),
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-07"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-security",
    title: "Security Audit Scheduled",
    description: "Third-party penetration test booked.",
    group: "completed",
    status: "done",
    priority: "high",
    labels: ["research"],
    memberIds: ["u-sara"],
    reporterId: "u-dexter",
    dueDate: iso("2026-08-01"),
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-08"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-ui-review",
    title: "UI Review",
    description: "Stakeholder walkthrough of the new interface.",
    group: "on_hold",
    status: "backlog",
    priority: "low",
    labels: ["design"],
    memberIds: ["u-maya"],
    reporterId: "u-dexter",
    dueDate: null,
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-09"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-backend",
    title: "Backend Integration",
    description: "Wire the dashboard to the metrics service.",
    group: "on_hold",
    status: "backlog",
    priority: "medium",
    labels: ["development"],
    memberIds: ["u-admin"],
    reporterId: "u-dexter",
    dueDate: null,
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-10"),
    subtasks: [],
    comments: [],
  },
  {
    id: "t-feedback",
    title: "User Feedback Review",
    description: "Synthesise findings from the latest research round.",
    group: "on_hold",
    status: "backlog",
    priority: "low",
    labels: ["research"],
    memberIds: ["u-sara"],
    reporterId: "u-dexter",
    dueDate: null,
    startDate: null,
    projectId: null,
    order: next(),
    createdAt: iso("2026-06-11"),
    subtasks: [],
    comments: [],
  },
];

/** Per-task Teams + Updates seed. Tasks not listed default to empty. */
const TASK_EXTRAS: Record<string, { teams: TeamKey[]; activity: Activity[] }> = {
  "t-api-docs": {
    teams: ["engineering", "design"],
    activity: [
      {
        id: "a-1",
        authorId: "u-dexter",
        createdAt: iso("2026-08-02"),
        kind: "change",
        field: "priority",
        from: "No Priority",
        to: "Urgent",
      },
      {
        id: "a-2",
        authorId: "u-dexter",
        createdAt: iso("2026-08-01"),
        kind: "post",
        note: "posted an update",
      },
    ],
  },
};

export const SEED_TASKS: Task[] = RAW_TASKS.map((t) => ({
  ...t,
  teams: TASK_EXTRAS[t.id]?.teams ?? [],
  activity: TASK_EXTRAS[t.id]?.activity ?? [],
}));

export const SEED_PROJECTS: Project[] = [
  { id: "p-home", name: "Design Homepage", priority: "high", leadId: "u-dexter", dueDate: iso("2026-09-12"), order: 0 },
  { id: "p-login", name: "Develop Login Feature", priority: "low", leadId: "u-cn", dueDate: iso("2026-09-15"), order: 1 },
  { id: "p-payment", name: "Test Payment Gateway", priority: "medium", leadId: null, dueDate: iso("2026-09-18"), order: 2 },
];
